### ISSUE TITLE
Zwischenfeedback

### ISSUE THREAD

**Issue by mabre** [ProPra16/programmierpraktikum-abschlussprojekt-freibier-in-raum-25-23-00-74#4]
Gute Nachricht zuerst: Bisher haben alle jeweils ausreichend viel beigetragen; macht weiter so, dann gibt es kein Problem mit dem Bestehen, sofern das Gesamtprojekt läuft.

Anmerkungen:
- Ihr habt einen Branch `interface2` und einen Branch `Interface2` auf dem Server. Sofern ihr euch darauf einigt, welcher davon der „richtige“ ist, ist das kein großes Problem.
- Im Branch `FileManager` wurde ein build-Ordner mit class-Dateien hochgeladen, die gehören aber nicht versioniert.
- Der Code auf dem `master` kompiliert gerade nicht, daher hab ich nicht geguckt, wie es aktuell um die Funktionalität steht.

```
"StateManager.java:(40, 22) java: constructor Code in class Code cannot be applied to given types;
  required: java.lang.String,java.lang.String,java.lang.String
  found: no arguments
  reason: actual and formal argument lists differ in length"
```

**Comment by lulan102** [comment]
Keine Sorge das ist alles bekannt und im Moment auch ok so.
Das mit Interface2 und interface2 ist mir leider erst nach dem pushen aufgefallen, ist aber kein Problem da wir sowieso mal wieder alles in den Master mergen wollen und entsprechend die bisherigen branches aufräumen wollen. Dementsprechend wird der Master dann auch wieder durchlaufen, da die entsprechenden Fehler schon in einem anderen branch gefixt wurden. Das mit dem Filemanger war uns auch klar, wir dachten aber das ist ok so, da es ja eh nur ein Branch ist in dem temporär gearbeitet wird.

**Comment by lulan102** [comment]
Ich hab eine Frage bezüglich Travis/Gradle etc. Ich hab es jetzt hinbekommen, dass er alles macht was gefordert ist (kompilieren, tests durchlaufen lassen, jar datei bauen). Die .jar Datei ist aber nicht im repository sondern natürlich im build Ordner von gradle, den sollen wir aber nicht auf git laden wenn ich das richtig verstanden habe. Soll dann die .jar Datei auch nicht auf git sein?

**Comment by mabre** [comment]
Wenn gefordert ist, dass ihr eine jar-Datei abgeben sollt, dann solltet ihr die (entgegen der Regel) committen (ich hab aber gerade in der Projektbeschreibung nichts zum Thema jar gefunden). Ansonsten reicht es mir, wenn in der Readme eine Beschreibung ist, wie man eine jar-Datei erstellen kann.

**Comment by lulan102** [comment]
Ich hatte das nur so aus der VL im Kopf. Ok das ist ja dann dank gradle kein Problem. Danke.

**Comment by mabre** [comment]
@Brookii @bayan100 @lulan102 @jaste111 bestanden
